### ISSUE TITLE
Error handling for unwrapping LLM amounts

### ISSUE THREAD

**Issue by kacperzuk-neti** [liberland/liberland_substrate#150]
Example: https://github.com/liberland/liberland_substrate/blob/72ce039edf2e0cb856edf98386e8e1cc3e9dbc4a/frame/llm/src/lib.rs#L233

In cases when `.try_into()` fails to convert amount into `T::Balance`, we should abort, as this is an overflow that shouldn't happen. Defaulting to 0 may have unforeseen consequences.

**Comment by flipchan** [comment]
let's try to remove all unwrap's

**Comment by flipchan** [comment]
" we should abort, as this is an overflow that shouldn't happen" an error should be thrown and it should be properly converted without unwrap

**Comment by kacperzuk-neti** [comment]
Largely handled in #190 , but still some places remain.

**Comment by kacperzuk-neti** [comment]
I can't find any remaining problematic unwraps
