### ISSUE TITLE
Replace local dependencies with the tagged repo

### ISSUE THREAD

**Issue by 3yekn** [liberland/liberland_substrate#16]
This repo has the dependencies physically stored within the directory structure. For example, the `Cargo.toml` looks like this: 

```toml
pallet-identity = { version = "4.0.0-dev", default-features = false, path = "../../../frame/identity" }
```

Instead, this should point to the repo and the appropriate tag, like this: 
```toml
pallet-identity = { git = "https://github.com/paritytech/substrate", tag = "polkadot-v.0.18.0", default-features = false" }
```

This should be done carefully, piece by piece, starting with the runtime

**Comment by flipchan** [comment]
todo: use the latest polkadot-v0.9.X packages, write runtime migrations > push it as an runtime upgrade

**Comment by kacperzuk-neti** [comment]
Done in #163
