### ISSUE TITLE
LLM asset integration is broken

### ISSUE THREAD

**Issue by kacperzuk-neti** [liberland/liberland_substrate#176]
`create_llm` in `pallet-llm` should create LLM asset in `pallet-assets` on first block: https://github.com/liberland/liberland_substrate/blob/main/frame/llm/src/lib.rs#L451

This however doesn't happen, as the `min_balance` cannot be set to 0, so `pallet_assets::Pallet::<T>::force_create` fails with `MinBalanceZero` error. All subsequent `pallet-assets` calls fail with `Unknown`, which makes sense, as it wasn't created. This goes unnoticed. As most of our codebase we don't have real error handling for assets calls, it's all covered up by `.unwrap_or_default()`.

This can be confirmed on testnets:
```
kacper@kacper-HP-ProBook-445-G7 ~> polkadot-js-api --ws wss://l2.laissez-faire.trade query.assets.asset 0
{
  "asset": null
}
kacper@kacper-HP-ProBook-445-G7 ~> polkadot-js-api --ws wss://l2.laissez-faire.trade query.assets.asset 1
{
  "asset": null
}
```

While the fix is easy (set `min_balance` to `1`), this raises a question - do we need pallet-assets, if we reimplement everything in LLM either way? Maybe we should drop it completely?

**Comment by flipchan** [comment]
the problem is that it doesnt get saved in the normal pallet-asset storage map

**Comment by flipchan** [comment]
can you publish the traceback of "fails with MinBalanceZero error"?

**Comment by kacperzuk-neti** [comment]
Just FYI, I've started fixing this, and asset not being created is a tip of the iceberg. Some calls have wrong origins and there are paths that lead to desync between what's stored in LLM pallet and what's stored in Assets pallet.

What do we need assets for?

**Comment by kacperzuk-neti** [comment]
I've submitted a draft PR showing more or less changes required to make pallet-assets work as expected.

However, this doesn't fix the issue of using `pallet-assets` directly - if someone sends extrinsics to `assets` directly using API or polkadot js app, it will get out of sync with LLM state. Not much we can do to fix this... we need to either remove assets integration or remove state from LLM and only use state from assets.

**Comment by kacperzuk-neti** [comment]
Also added draft PR that drops support for pallet-assets from LLM. So we can compare how much impact each potential resolution has.

**Comment by kacperzuk-neti** [comment]
Closing, as #190 is on track to be merged.
