### ISSUE TITLE
Error with NoFallback elections

### ISSUE THREAD

**Issue by 3yekn** [liberland/liberland_substrate#18]
I see this error. What should the fallback be? 

8:01:42 👶 Next epoch starts at slot 549329008
Mar 22 18:01:42 test liberland[2500463]: 2022-03-22 18:01:42 [#33406] 🗳  Failed to finalize election round. reason ElectionError::Fallback("NoFallback.")
Mar 22 18:01:42 test liberland[2500463]: 2022-03-22 18:01:42 [#33406] 🗳  Entering emergency mode: ElectionError::Fallback("NoFallback.")
Mar 22 18:01:42 test liberland[2500463]: 2022-03-22 18:01:42 [33406] 💸 election provider failed due to ElectionError::Fallback("NoFallback.")

**Comment by flipchan** [comment]
seems to be fixed
