### ISSUE TITLE
Need to fix Hazlitt chain explorer

### ISSUE THREAD

**Issue by SHA888** [liberland/liberland_substrate#217]
View live chain: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fl2.laissez-faire.trade#/explorer URL on the [Readme](https://github.com/liberland/liberland_substrate/blob/main/README.md#current-bootnodes) doesn't work

**Comment by kacperzuk-neti** [comment]
Hazlitt is being deprecated, use PowellGoHome instead: https://polkadot.js.org/apps/?rpc=wss%253A%252F%252Ftestchain.liberland.org#/explorer . Sorry for the delay in updating docs, I'll sort this out.

Thanks for the report!

**Comment by kacperzuk-neti** [comment]
Docs fixed.
