### ISSUE TITLE
Runtime and genesis parameters tweak

### ISSUE THREAD

**Issue by amatsonkali** [liberland/liberland_substrate#29]
# Runtime
## Constants and fees handler
- [x] Change runtime constants if required (seconds per block, epoch duration, etc).
- [x] Fees treasury/validator % (Currently at 80% treasury, 20% validator)

## Staking 
- [x] Maximum nominations (currently none)
- [x] ~Sessions per era (currently at 6, not relevant)~
- [x] Bonding duration (currently at 28 days, assuming epoch of 1hr. it might need to be reworked)
- [x] MaxNominatorRewardedPerValidator (currently at 256)
- [x] Reward remainder (currently set to Treasury. Waiting for a decision to be made)
- [x] Reward curve (Waiting for a decision to be made).

## Treasury
- [x] SpendPeriod (currently at 1 day)
- [x] Burn rate (currently at 50%)
- [x] Council approval rate (currently at 60% or root)
- [x] Council denial rate (currently at 50% or root)

## State trie migration
- [ ] SignedFilter (currently at EnsureSigned<Self::AccountId>, it can result on a DOS attack)

# Genesis spec
- [x] Swap the controller/stash accounts on the "stakers" array
- [ ] Change the primary token name
- [ ] Fund accounts and treasury (sum needs to be as close as 7 million)
- [ ] Populate the Council and technicalCommittee (society as optional)
- [ ] Optional: Add new validators at genesis

**Comment by flipchan** [comment]
Bonding duration - Minimum amount of days

**Comment by flipchan** [comment]
https://github.com/liberland/liberland_substrate/compare/lld_bump?expand=1

**Comment by flipchan** [comment]
not active, anyone can take this
