### ISSUE TITLE
Will the Liberland blockchain be quantum-resistant?

### ISSUE THREAD

**Issue by LiberlandHacker** [liberland/liberland_substrate#30]
With quantum computing on the rise, is the current iteration of the Liberland blockchain resistant against anti-encryption attacks by quantum computers? 

If not, what is being done about it?

**Comment by flipchan** [comment]
@LiberlandHacker Great Question! If you look into how addresses are being generated and the underlying elliptic curve implementations, the answer to this is yes, due to how the keys are being generation.

**Comment by flipchan** [comment]
@LiberlandHacker find more info here: https://docs.substrate.io/v3/advanced/cryptography/

**Comment by flipchan** [comment]
@LiberlandHacker this is also a concern that should be battle tested before a final verdict is given. Feel free to submit any findings that might be a concern.

**Comment by flipchan** [comment]
closing this issue
