### ISSUE TITLE
Council Voting LLD --> LLM

### ISSUE THREAD

**Issue by michalptacnik** [liberland/liberland_substrate#62]
Hello Filip,

The voting for Council currently happens using LLD. We should make it work using LLM. Could you look into it?

**Comment by flipchan** [comment]
This will require a rewrite of the council pallet, as this is the council and not the citizen that are voting

**Comment by michalptacnik** [comment]
I am sorry, this is a misunderstanding, what I mean is the following:
When a Citizen votes for the Council, they are voting currently with their LLD. This is obviously unacceptable, as LLM, and not LLD, is the political token. 
Solution: To do as we did with the referendum and to have the Citizen vote with LLM.

Council doesn't vote with LLD or LLM, they use head count, one Council member, one vote. So that is irrelevant for the issue.  Can you do this Filip?

**Comment by flipchan** [comment]
Voting for council is now done in llm
