### ISSUE TITLE
Law Pallet

### ISSUE THREAD

**Issue by michalptacnik** [liberland/liberland_substrate#64]
Hello Dorian!

The Law Pallet should be created before the MVP launch. It should allow to store (references to) laws and allow for multiple types of legislature.
It should also allow users to
- create Proposals without having to select functions and methods;
- create Proposals without going through the preimage hash step
- /but not lose the security provided by the preimage hash.

**Comment by flipchan** [comment]
What you are describing is two different things:
create Proposals without having to select functions and methods;
create Proposals without going through the preimage hash step
but not lose the security provided by the preimage hash.

These functions can all be done with a nice UI. The law pallet will interact with laws and should be separated from this issue

**Comment by michalptacnik** [comment]
Well, yes. There is an UI component, and Dorian is busy with that (or will be). But there has to be a Law Pallet. We need to create functions which you trigger in order to create legislature and then prepare a system of "tags" for the approved Laws. So that, when we later API into the chain, we can run queries like "Select all Laws from Liberland Smart Chain". Makes sense?

**Comment by DorianSternVukotic** [comment]
Also setup weights and lock to origin of referendum

**Comment by flipchan** [comment]
Pallet created, needs to get pushed

**Comment by kacperzuk-neti** [comment]
Everything (blockchain-side) implemented.
