### ISSUE TITLE
Configure Staking rewards curve

### ISSUE THREAD

**Issue by amatsonkali** [liberland/liberland_substrate#9]
**Suggested Solution**

- [x] Estimate the rewards/inflation curve based on the provided Tokenomics table, considering the configurable parameters on the staking pallet:
```pallet_staking_reward_curve::build! {
    const REWARD_CURVE: PiecewiseLinear<'static> = curve!(
        min_inflation: 0_025_000,
        max_inflation: 0_100_000,
        ideal_stake: 0_500_000,
        falloff: 0_050_000,
        max_piece_count: 40,
        test_precision: 0_005_000,
    );
}
```
- [ ] Include the curve as a staking pallet configuration on a fairly updated substrate environment/project.
- [ ] Code at least 3 unit tests in order to evaluate the edge cases.

**Comment by flipchan** [comment]
close for now
